### ISSUE TITLE
Can you provide a screenshot.  Does 'squirrel' language gets some kind of highlighting also? 

### ISSUE THREAD

**Issue by habi498** [dragomano/Code-Highlighting#5]
Hi we are from forum.vc-mp.org
The default highlighting given by SMF is not good.  If it looks okay,  i will request the admins to have a look.

**Comment by dragomano** [comment]
You can try using [PrismJS for SMF](https://github.com/dragomano/PrismJS-for-SMF). It seems to support Squirrel language.

**Comment by habi498** [comment]
Thank you
